### ISSUE TITLE
Using GitHub CLI

### ISSUE THREAD

**Issue by szepeviktor** [widoz/github-artifacts-action#6]
Hello!
GitHub CLI is included in every GHA image.
Artifacts could be zipped then uploaded as release assets.
`gh release upload ${{ github.ref_name }} asset.zip`

**Comment by widoz** [comment]
Hi, thanks for pointing it out. I have to admit I never used such a command, the usage I do of the cli is very limited.

If I get it right with this command I can upload additional files I want to attach to the release but they are not automatically downloaded and placed within the right dir when I install the package via composer.

The goal of this action is to allow devs to automatically build and push artifacts (assets build) back into the repository. The fact that the example in the readme shows the workflow running for a tag is just one of the possibilities.

Can I do the same with the GH command? I did a quick research and It seems not. But I've not tried the process.

**Comment by szepeviktor** [comment]
I was just saying that all that can be done in 3 commands.
```yaml
run: |
  npm run build
  zip ....
  gh release upload ...
```

**Comment by szepeviktor** [comment]
But I see that command line is highly unpopular in these days, and people like your action more than reading man pages.
